project.packages=io.cyborgcode.roa.usage
api.config.file=config-qa
framework.config.file=config-qa
test.data.file=test_data-qa
logFileName=logs/ui-example.log
log4j2.scriptEnableLanguages=javascript
extended.logging=false
