project.packages=io.cyborgcode.roa.usage
api.config.file=config-QA
framework.config.file=config-QA
test.data.file=test_data-QA
logFileName=logs/ui-example.log
log4j2.scriptEnableLanguages=javascript
extended.logging=false
